### ISSUE TITLE
no access to some files on external server

### ISSUE THREAD

**Issue by migabriels** [rcolpo/PGP_Reconstruction#1]
Hi, 

I tried to use the tool, but it seems that I don't have permission to access some of the files on the external server that will be downloaded during the first run. This applies to the files swiss90tremble50SeqInfo.pickle, swiss90Tremble50WithRhea.fasta and SwissProtIds.pickle. Also, the URL to cplex_solver.py does not exists on the external server. 

Do you have an idea on how I can solve this problem? Thanks!

**Comment by rcolpo** [comment]
Dear migabriels,
This problem is now solved, and you should be able to download the latest version of the databases from the server.
Kind regards,
Rodrigo.
